# PINN Configuration with PDE-specific settings
# Configuration file for Physics-Informed Neural Networks

# Device Configuration
device: "mps"  # Options: "cuda", "mps", "cpu"

# Model Architecture
model:
  architecture: "fourier"  # Options: "fourier", "resnet", "siren", "autoencoder", "feedforward"
  input_dim: 2  # (x, t)
  hidden_dim: 124
  output_dim: 1  # u(x,t)
  num_layers: 8
  activation: "relu"  # Options: "tanh", "relu", "gelu"
  fourier_features: true
  fourier_scale: 10.0
  dropout: 0.1
  layer_norm: true

# Default PDE type to use
pde_type: "wave"  # Options: "heat", "wave", "burgers", "convection", "kdv", "allen_cahn", "cahn_hilliard", "black_scholes", "pendulum"

# PDE-specific configurations
pde_configs:
  # Heat Equation Configuration
  heat:
    name: "Heat Equation"
    parameters:
      alpha: 0.01  # Thermal diffusivity coefficient
    domain: [[0.0, 1.0]]  # Spatial domain [[x_min, x_max]] for 1D
    time_domain: [0.0, 1.0]  # Temporal domain [t_min, t_max]
    dimension: 1
    initial_condition:
      type: "sine"
      amplitude: 1.0
      frequency: 1.0
    boundary_conditions:
      dirichlet:
        type: "fixed"
        value: 0.0
    exact_solution:
      type: "sine"
      amplitude: 1.0
      frequency: 1.0
  
  # Wave Equation Configuration
  wave:
    name: "Wave Equation"
    parameters:
      c: 1.0  # Wave speed
    domain: [[0.0, 1.0]]
    time_domain: [0.0, 1.0]
    dimension: 1
    initial_condition:
      type: "sine"
      amplitude: 1.0
      frequency: 1.0
    boundary_conditions:
      dirichlet:
        type: "fixed"
        value: 0.0
    exact_solution:
      type: "sine"
      amplitude: 1.0
      frequency: 1.0
  
  # Burgers Equation Configuration
  burgers:
    name: "Burgers Equation"
    parameters:
      viscosity: 0.01  # Viscosity coefficient
    domain: [[-1.0, 1.0]]
    time_domain: [0.0, 1.0]
    dimension: 1
    initial_condition:
      type: "sine"
      amplitude: -1.0
      frequency: 1.0
    boundary_conditions:
      dirichlet:
        type: "fixed"
        value: 0.0
    # No simple exact solution for Burgers
  
  # Convection Equation Configuration
  convection:
    name: "Convection Equation"
    parameters:
      velocity: [1.0]  # Convection velocity vector [vx]
    domain: [[0.0, 2.0]]
    time_domain: [0.0, 1.0]
    dimension: 1
    initial_condition:
      type: "sine"
      amplitude: 1.0
      frequency: 1.0
    boundary_conditions:
      dirichlet:
        type: "periodic"
    exact_solution:
      type: "sine"
      amplitude: 1.0
      frequency: 1.0
  
  # KdV Equation Configuration
  kdv:
    name: "KdV Equation"
    parameters:
      alpha: 6.0  # Nonlinear coefficient
      beta: 1.0   # Dispersion coefficient
      speed: 1.0  # Wave speed
    domain: [[-15.0, 15.0]]
    time_domain: [0.0, 5.0]
    dimension: 1
    initial_condition:
      type: "soliton"
      speed: 1.0
    boundary_conditions:
      dirichlet:
        type: "fixed"
        value: 0.0
    exact_solution:
      type: "soliton"
      speed: 1.0
  
  # Allen-Cahn Equation Configuration
  allen_cahn:
    name: "Allen-Cahn Equation"
    parameters:
      epsilon: 0.1  # Interface width parameter
      reaction_rate: 1.0  # Reaction rate
    domain: [[-1.0, 1.0]]
    time_domain: [0.0, 1.0]
    dimension: 1
    initial_condition:
      type: "tanh"
    boundary_conditions:
      dirichlet:
        type: "fixed"
        value: 0.0
    exact_solution:
      type: "tanh"
  
  # Cahn-Hilliard Equation Configuration
  cahn_hilliard:
    name: "Cahn-Hilliard Equation"
    parameters:
      mobility: 1.0  # Mobility coefficient
      kappa: 0.01  # Interface energy coefficient
    domain: [[0.0, 1.0]]
    time_domain: [0.0, 1.0]
    dimension: 1
    initial_condition:
      type: "random"
      amplitude: 0.1
    boundary_conditions:
      dirichlet:
        type: "fixed"
        value: 0.0
      neumann:
        type: "zero"
    # No simple exact solution for Cahn-Hilliard
  
  # Black-Scholes Equation Configuration
  black_scholes:
    name: "Black-Scholes Equation"
    parameters:
      sigma: 0.2  # Volatility
      r: 0.05  # Risk-free interest rate
    domain: [[0.0, 200.0]]  # Stock price domain
    time_domain: [0.0, 1.0]  # Time to maturity (years)
    dimension: 1
    initial_condition:
      type: "option"
      strike: 100.0
      option_type: "call"
    boundary_conditions:
      dirichlet:
        type: "custom"
    exact_solution:
      type: "black_scholes"
      strike: 100.0
      option_type: "call"
  
  # Pendulum Equation Configuration
  pendulum:
    name: "Pendulum Equation"
    parameters:
      g: 9.81  # Gravitational constant
      L: 1.0   # Pendulum length
      damping: 0.1  # Damping coefficient
    domain: [[0.0, 2.0 * 3.14159]]  # Angle domain
    time_domain: [0.0, 10.0]
    dimension: 1
    initial_condition:
      type: "sine"
      amplitude: 0.5
      frequency: 1.0
    boundary_conditions:
      dirichlet:
        type: "periodic"
    # No simple exact solution for nonlinear pendulum

# Training Configuration
training:
  num_epochs: 1000
  batch_size: 1000
  num_collocation_points: 10000
  validation_frequency: 100
  early_stopping:
    enabled: true
    patience: 10
  optimizer_config:
    name: "adam"
    lr: 0.001
    weight_decay: 1.0e-5
  rl_update_frequency: 10  # Update RL agent every N epochs

# Reinforcement Learning Configuration
rl:
  enabled: true
  state_dim: 2  # (x, t)
  action_dim: 1  # Sampling probability
  hidden_dim: 64
  learning_rate: 0.001
  gamma: 0.99
  epsilon_start: 1.0
  epsilon_end: 0.01
  epsilon_decay: 0.995
  memory_size: 10000
  batch_size: 64
  target_update: 100
  reward_weights:
    residual: 1.0
    boundary: 1.0
    initial: 1.0
    exploration: 0.1

# Evaluation Configuration
evaluation:
  num_points: 100  # Number of points for evaluation
  metrics:
    - "l2_error"
    - "max_error"
    - "mean_error"
  save_plots: true
  plot_frequency: 100  # Plot every N epochs

# Logging Configuration
logging:
  level: "INFO"
  save_tensorboard: true
  log_frequency: 100

# Paths
paths:
  results_dir: "results"
  log_dir: "logs"
